---
  name: Publish
  on:  # yamllint disable-line rule:truthy
    push:
      tags:
        - v*
  jobs:
    publish_main:
      name: Publish main branch artefacts
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version:  '1.21.x'
        - name: release
          uses: actions/create-release@v1
          id: create_release
          with:
            draft: false
            prerelease: false
            release_name: ${{ github.ref }}
            tag_name: ${{ github.ref }}
            body_path: CHANGELOG.md
          env:
            GITHUB_TOKEN: ${{ github.token }}
        - name: Install dependencies
          run: GOOS=linux GOARCH=amd64 go build ./cmd/alertmanager
        - name: package dependencies
          run: tar -cf alertmanager.linux-amd64.tar.gz alertmanager
        - name: upload linux artifact
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ github.token }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ./alertmanager.linux-amd64.tar.gz
            asset_name: alertmanager.linux-amd64.tar.gz
            asset_content_type: application/gzip
